/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Education {
  'institution' : string,
  'graduationYear' : bigint,
  'degree' : string,
}
export type ExternalBlob = Uint8Array;
export interface JobRole {
  'title' : string,
  'description' : string,
  'requiredSkills' : Array<Skill>,
}
export interface Resume {
  'blob' : ExternalBlob,
  'recommendations' : [] | [Array<string>],
  'user' : Principal,
  'education' : [] | [Array<Education>],
  'uploadTimestamp' : Time,
  'fileId' : string,
  'experiences' : [] | [Array<WorkExperience>],
  'skills' : [] | [Array<Skill>],
}
export interface ResumeData {
  'yearsOfExperience' : bigint,
  'contactInfo' : [] | [string],
  'name' : string,
  'education' : [] | [Array<Education>],
  'workExperience' : [] | [Array<WorkExperience>],
  'certifications' : [] | [Array<string>],
  'skills' : [] | [Array<string>],
}
export interface ResumeScore {
  'completenessScore' : bigint,
  'feedback' : string,
  'totalScore' : bigint,
  'skillRelevanceScore' : bigint,
  'contentQualityScore' : bigint,
  'formattingScore' : bigint,
}
export interface Skill {
  'name' : string,
  'level' : SkillLevel,
  'category' : SkillCategory,
}
export type SkillCategory = { 'technical' : null } |
  { 'softSkills' : null };
export type SkillLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type Time = bigint;
export interface UserProfile {
  'contact' : [] | [string],
  'name' : string,
  'education' : [] | [string],
  'email' : [] | [string],
  'experience' : [] | [string],
  'totalSkills' : [] | [bigint],
  'isComplete' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkExperience {
  'role' : string,
  'durationMonths' : bigint,
  'company' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJobRole' : ActorMethod<[string, string, Array<Skill>], undefined>,
  'analyzeResume' : ActorMethod<
    [bigint, bigint, bigint, bigint, string],
    ResumeScore
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateSkillGaps' : ActorMethod<[string, string], Array<string>>,
  'deleteResume' : ActorMethod<[string], undefined>,
  'getAllSkills' : ActorMethod<[Principal], Array<Skill>>,
  'getCallerResumes' : ActorMethod<[], Array<Resume>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobRoles' : ActorMethod<[], Array<JobRole>>,
  'getResume' : ActorMethod<[string], [] | [Resume]>,
  'getResumeData' : ActorMethod<[], [] | [ResumeData]>,
  'getResumes' : ActorMethod<[Principal], Array<Resume>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeJobRole' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setResumeData' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [Array<string>],
      [] | [Array<WorkExperience>],
      [] | [Array<Education>],
      bigint,
      [] | [Array<string>],
    ],
    undefined
  >,
  'updateJobRole' : ActorMethod<[string, string, Array<Skill>], undefined>,
  'uploadResume' : ActorMethod<
    [
      string,
      ExternalBlob,
      Array<WorkExperience>,
      Array<Skill>,
      Array<Education>,
      Array<string>,
    ],
    undefined
  >,
  'validateResume' : ActorMethod<
    [
      [] | [Array<WorkExperience>],
      [] | [Array<Skill>],
      [] | [Array<Education>],
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];