/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SkillLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const SkillCategory = IDL.Variant({
  'technical' : IDL.Null,
  'softSkills' : IDL.Null,
});
export const Skill = IDL.Record({
  'name' : IDL.Text,
  'level' : SkillLevel,
  'category' : SkillCategory,
});
export const ResumeScore = IDL.Record({
  'completenessScore' : IDL.Nat,
  'feedback' : IDL.Text,
  'totalScore' : IDL.Nat,
  'skillRelevanceScore' : IDL.Nat,
  'contentQualityScore' : IDL.Nat,
  'formattingScore' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Education = IDL.Record({
  'institution' : IDL.Text,
  'graduationYear' : IDL.Int,
  'degree' : IDL.Text,
});
export const Time = IDL.Int;
export const WorkExperience = IDL.Record({
  'role' : IDL.Text,
  'durationMonths' : IDL.Nat,
  'company' : IDL.Text,
});
export const Resume = IDL.Record({
  'blob' : ExternalBlob,
  'recommendations' : IDL.Opt(IDL.Vec(IDL.Text)),
  'user' : IDL.Principal,
  'education' : IDL.Opt(IDL.Vec(Education)),
  'uploadTimestamp' : Time,
  'fileId' : IDL.Text,
  'experiences' : IDL.Opt(IDL.Vec(WorkExperience)),
  'skills' : IDL.Opt(IDL.Vec(Skill)),
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'education' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'experience' : IDL.Opt(IDL.Text),
  'totalSkills' : IDL.Opt(IDL.Nat),
  'isComplete' : IDL.Bool,
});
export const JobRole = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'requiredSkills' : IDL.Vec(Skill),
});
export const ResumeData = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'contactInfo' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'education' : IDL.Opt(IDL.Vec(Education)),
  'workExperience' : IDL.Opt(IDL.Vec(WorkExperience)),
  'certifications' : IDL.Opt(IDL.Vec(IDL.Text)),
  'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJobRole' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Skill)], [], []),
  'analyzeResume' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [ResumeScore],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateSkillGaps' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'deleteResume' : IDL.Func([IDL.Text], [], []),
  'getAllSkills' : IDL.Func([IDL.Principal], [IDL.Vec(Skill)], ['query']),
  'getCallerResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
  'getResume' : IDL.Func([IDL.Text], [IDL.Opt(Resume)], ['query']),
  'getResumeData' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
  'getResumes' : IDL.Func([IDL.Principal], [IDL.Vec(Resume)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeJobRole' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setResumeData' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Vec(WorkExperience)),
        IDL.Opt(IDL.Vec(Education)),
        IDL.Nat,
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [],
      [],
    ),
  'updateJobRole' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Skill)], [], []),
  'uploadResume' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Vec(WorkExperience),
        IDL.Vec(Skill),
        IDL.Vec(Education),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'validateResume' : IDL.Func(
      [
        IDL.Opt(IDL.Vec(WorkExperience)),
        IDL.Opt(IDL.Vec(Skill)),
        IDL.Opt(IDL.Vec(Education)),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SkillLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const SkillCategory = IDL.Variant({
    'technical' : IDL.Null,
    'softSkills' : IDL.Null,
  });
  const Skill = IDL.Record({
    'name' : IDL.Text,
    'level' : SkillLevel,
    'category' : SkillCategory,
  });
  const ResumeScore = IDL.Record({
    'completenessScore' : IDL.Nat,
    'feedback' : IDL.Text,
    'totalScore' : IDL.Nat,
    'skillRelevanceScore' : IDL.Nat,
    'contentQualityScore' : IDL.Nat,
    'formattingScore' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Education = IDL.Record({
    'institution' : IDL.Text,
    'graduationYear' : IDL.Int,
    'degree' : IDL.Text,
  });
  const Time = IDL.Int;
  const WorkExperience = IDL.Record({
    'role' : IDL.Text,
    'durationMonths' : IDL.Nat,
    'company' : IDL.Text,
  });
  const Resume = IDL.Record({
    'blob' : ExternalBlob,
    'recommendations' : IDL.Opt(IDL.Vec(IDL.Text)),
    'user' : IDL.Principal,
    'education' : IDL.Opt(IDL.Vec(Education)),
    'uploadTimestamp' : Time,
    'fileId' : IDL.Text,
    'experiences' : IDL.Opt(IDL.Vec(WorkExperience)),
    'skills' : IDL.Opt(IDL.Vec(Skill)),
  });
  const UserProfile = IDL.Record({
    'contact' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'education' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'experience' : IDL.Opt(IDL.Text),
    'totalSkills' : IDL.Opt(IDL.Nat),
    'isComplete' : IDL.Bool,
  });
  const JobRole = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'requiredSkills' : IDL.Vec(Skill),
  });
  const ResumeData = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'contactInfo' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'education' : IDL.Opt(IDL.Vec(Education)),
    'workExperience' : IDL.Opt(IDL.Vec(WorkExperience)),
    'certifications' : IDL.Opt(IDL.Vec(IDL.Text)),
    'skills' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJobRole' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Skill)], [], []),
    'analyzeResume' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [ResumeScore],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateSkillGaps' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'deleteResume' : IDL.Func([IDL.Text], [], []),
    'getAllSkills' : IDL.Func([IDL.Principal], [IDL.Vec(Skill)], ['query']),
    'getCallerResumes' : IDL.Func([], [IDL.Vec(Resume)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobRoles' : IDL.Func([], [IDL.Vec(JobRole)], ['query']),
    'getResume' : IDL.Func([IDL.Text], [IDL.Opt(Resume)], ['query']),
    'getResumeData' : IDL.Func([], [IDL.Opt(ResumeData)], ['query']),
    'getResumes' : IDL.Func([IDL.Principal], [IDL.Vec(Resume)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeJobRole' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setResumeData' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Vec(WorkExperience)),
          IDL.Opt(IDL.Vec(Education)),
          IDL.Nat,
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [],
        [],
      ),
    'updateJobRole' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(Skill)], [], []),
    'uploadResume' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Vec(WorkExperience),
          IDL.Vec(Skill),
          IDL.Vec(Education),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'validateResume' : IDL.Func(
        [
          IDL.Opt(IDL.Vec(WorkExperience)),
          IDL.Opt(IDL.Vec(Skill)),
          IDL.Opt(IDL.Vec(Education)),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };