/**
 * PDF Generator Service
 * Generates downloadable PDF reports of skill gap analysis with personalized resume data
 */

import type { ExperienceEntry, EducationEntry } from './nlpService';

export interface AnalysisReportData {
  jobRole: {
    title: string;
  };
  matchPercentage: number;
  matchingSkills: Array<{ name: string; level: string; category: string }>;
  missingSkills: Array<{ name: string; level: string; category: string }>;
  recommendations: Array<{
    skill: string;
    courses: Array<{ title: string; provider: string }>;
    projects: Array<{ title: string; description: string }>;
  }>;
  resumeContext?: {
    experience: ExperienceEntry[];
    education: EducationEntry[];
    certifications: string[];
    experienceLevel: string;
    totalYearsExperience: number;
  };
}

export async function generateAnalysisReport(analysisData: AnalysisReportData): Promise<void> {
  try {
    // Create a personalized text-based report
    // In production, you would use a library like jsPDF or react-pdf
    
    const reportContent = `
SKILL GAP ANALYSIS REPORT
Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}

================================================================================
JOB ROLE: ${analysisData.jobRole.title}
================================================================================

OVERALL MATCH: ${analysisData.matchPercentage}%

${analysisData.resumeContext ? `
CANDIDATE PROFILE:
- Experience Level: ${analysisData.resumeContext.experienceLevel.toUpperCase()}
- Total Years of Experience: ${analysisData.resumeContext.totalYearsExperience} years

WORK EXPERIENCE (${analysisData.resumeContext.experience.length} entries):
${analysisData.resumeContext.experience.map((exp, idx) => `
${idx + 1}. ${exp.title}${exp.company ? ` at ${exp.company}` : ''}
   ${exp.duration || ''}
   ${exp.description.substring(0, 200)}${exp.description.length > 200 ? '...' : ''}
`).join('\n')}

EDUCATION (${analysisData.resumeContext.education.length} entries):
${analysisData.resumeContext.education.map((edu, idx) => `
${idx + 1}. ${edu.degree}
   ${edu.institution || ''}
   ${edu.year || ''}
`).join('\n')}

${analysisData.resumeContext.certifications.length > 0 ? `
CERTIFICATIONS (${analysisData.resumeContext.certifications.length}):
${analysisData.resumeContext.certifications.map((cert, idx) => `${idx + 1}. ${cert}`).join('\n')}
` : ''}
` : ''}

================================================================================
MATCHING SKILLS (${analysisData.matchingSkills.length}):
================================================================================
${analysisData.matchingSkills.map((s, idx) => `${idx + 1}. ${s.name} - Level: ${s.level}, Category: ${s.category}`).join('\n')}

================================================================================
MISSING SKILLS (${analysisData.missingSkills.length}):
================================================================================
${analysisData.missingSkills.map((s, idx) => `${idx + 1}. ${s.name} - Level: ${s.level}, Category: ${s.category}`).join('\n')}

================================================================================
PERSONALIZED RECOMMENDATIONS:
================================================================================
${analysisData.recommendations.map((r, idx) => `
${idx + 1}. SKILL: ${r.skill}

   Recommended Courses:
${r.courses.map((c, cidx) => `   ${cidx + 1}. ${c.title} (${c.provider})`).join('\n')}

   Suggested Projects:
${r.projects.map((p, pidx) => `   ${pidx + 1}. ${p.title}
      ${p.description}`).join('\n')}
`).join('\n')}

================================================================================
This personalized report was generated based on your unique resume content.
Each analysis is tailored to your specific skills, experience, and background.

Report generated by SkillGap Analyzer
Built with love using caffeine.ai
    `.trim();
    
    // Create a blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `skill-gap-analysis-${analysisData.jobRole.title.replace(/\s+/g, '-')}-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate report');
  }
}
