/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Education {
    institution: string;
    graduationYear: bigint;
    degree: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface JobRole {
    title: string;
    description: string;
    requiredSkills: Array<Skill>;
}
export interface Skill {
    name: string;
    level: SkillLevel;
    category: SkillCategory;
}
export interface WorkExperience {
    role: string;
    durationMonths: bigint;
    company: string;
}
export interface Resume {
    blob: ExternalBlob;
    recommendations?: Array<string>;
    user: Principal;
    education?: Array<Education>;
    uploadTimestamp: Time;
    fileId: string;
    experiences?: Array<WorkExperience>;
    skills?: Array<Skill>;
}
export interface ResumeData {
    yearsOfExperience: bigint;
    contactInfo?: string;
    name: string;
    education?: Array<Education>;
    workExperience?: Array<WorkExperience>;
    certifications?: Array<string>;
    skills?: Array<string>;
}
export interface UserProfile {
    contact?: string;
    name: string;
    education?: string;
    email?: string;
    experience?: string;
    totalSkills?: bigint;
    isComplete: boolean;
}
export interface ResumeScore {
    completenessScore: bigint;
    feedback: string;
    totalScore: bigint;
    skillRelevanceScore: bigint;
    contentQualityScore: bigint;
    formattingScore: bigint;
}
export enum SkillCategory {
    technical = "technical",
    softSkills = "softSkills"
}
export enum SkillLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addJobRole(title: string, description: string, requiredSkills: Array<Skill>): Promise<void>;
    analyzeResume(completenessScore: bigint, contentQualityScore: bigint, formattingScore: bigint, skillRelevanceScore: bigint, feedback: string): Promise<ResumeScore>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateSkillGaps(documentId: string, jobRole: string): Promise<Array<string>>;
    deleteResume(documentId: string): Promise<void>;
    getAllSkills(user: Principal): Promise<Array<Skill>>;
    getCallerResumes(): Promise<Array<Resume>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJobRoles(): Promise<Array<JobRole>>;
    getResume(documentId: string): Promise<Resume | null>;
    getResumeData(): Promise<ResumeData | null>;
    getResumes(user: Principal): Promise<Array<Resume>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeJobRole(title: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setResumeData(name: string, contactInfo: string | null, skills: Array<string> | null, workExperience: Array<WorkExperience> | null, education: Array<Education> | null, yearsOfExperience: bigint, certifications: Array<string> | null): Promise<void>;
    updateJobRole(title: string, description: string, requiredSkills: Array<Skill>): Promise<void>;
    uploadResume(documentId: string, blob: ExternalBlob, experiences: Array<WorkExperience>, skills: Array<Skill>, education: Array<Education>, recommendations: Array<string>): Promise<void>;
    validateResume(experiences: Array<WorkExperience> | null, skills: Array<Skill> | null, education: Array<Education> | null): Promise<boolean>;
}
import type { Education as _Education, ExternalBlob as _ExternalBlob, JobRole as _JobRole, Resume as _Resume, ResumeData as _ResumeData, Skill as _Skill, SkillCategory as _SkillCategory, SkillLevel as _SkillLevel, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WorkExperience as _WorkExperience, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addJobRole(arg0: string, arg1: string, arg2: Array<Skill>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJobRole(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJobRole(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async analyzeResume(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: string): Promise<ResumeScore> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeResume(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeResume(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateSkillGaps(arg0: string, arg1: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateSkillGaps(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateSkillGaps(arg0, arg1);
            return result;
        }
    }
    async deleteResume(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async getAllSkills(arg0: Principal): Promise<Array<Skill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSkills(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSkills(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerResumes(): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerResumes();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerResumes();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobRoles(): Promise<Array<JobRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobRoles();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobRoles();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResume(arg0: string): Promise<Resume | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResume(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResume(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumeData(): Promise<ResumeData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeData();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeData();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResumes(arg0: Principal): Promise<Array<Resume>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumes(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumes(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeJobRole(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeJobRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeJobRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setResumeData(arg0: string, arg1: string | null, arg2: Array<string> | null, arg3: Array<WorkExperience> | null, arg4: Array<Education> | null, arg5: bigint, arg6: Array<string> | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setResumeData(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setResumeData(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateJobRole(arg0: string, arg1: string, arg2: Array<Skill>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobRole(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobRole(arg0, arg1, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadResume(arg0: string, arg1: ExternalBlob, arg2: Array<WorkExperience>, arg3: Array<Skill>, arg4: Array<Education>, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadResume(arg0, await to_candid_ExternalBlob_n51(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadResume(arg0, await to_candid_ExternalBlob_n51(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async validateResume(arg0: Array<WorkExperience> | null, arg1: Array<Skill> | null, arg2: Array<Education> | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateResume(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateResume(to_candid_opt_n49(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_JobRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobRole): JobRole {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_ResumeData_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResumeData): ResumeData {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_Resume_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resume): Promise<Resume> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SkillCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillCategory): SkillCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SkillLevel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillLevel): SkillLevel {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Education>]): Array<Education> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_WorkExperience>]): Array<WorkExperience> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Skill>]): Array<Skill> | null {
    return value.length === 0 ? null : from_candid_vec_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resume]): Promise<Resume | null> {
    return value.length === 0 ? null : await from_candid_Resume_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResumeData]): ResumeData | null {
    return value.length === 0 ? null : from_candid_ResumeData_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    level: _SkillLevel;
    category: _SkillCategory;
}): {
    name: string;
    level: SkillLevel;
    category: SkillCategory;
} {
    return {
        name: value.name,
        level: from_candid_SkillLevel_n20(_uploadFile, _downloadFile, value.level),
        category: from_candid_SkillCategory_n22(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    recommendations: [] | [Array<string>];
    user: Principal;
    education: [] | [Array<_Education>];
    uploadTimestamp: _Time;
    fileId: string;
    experiences: [] | [Array<_WorkExperience>];
    skills: [] | [Array<_Skill>];
}): Promise<{
    blob: ExternalBlob;
    recommendations?: Array<string>;
    user: Principal;
    education?: Array<Education>;
    uploadTimestamp: Time;
    fileId: string;
    experiences?: Array<WorkExperience>;
    skills?: Array<Skill>;
}> {
    return {
        blob: await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value.blob),
        recommendations: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.recommendations)),
        user: value.user,
        education: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.education)),
        uploadTimestamp: value.uploadTimestamp,
        fileId: value.fileId,
        experiences: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.experiences)),
        skills: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.skills))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: [] | [string];
    name: string;
    education: [] | [string];
    email: [] | [string];
    experience: [] | [string];
    totalSkills: [] | [bigint];
    isComplete: boolean;
}): {
    contact?: string;
    name: string;
    education?: string;
    email?: string;
    experience?: string;
    totalSkills?: bigint;
    isComplete: boolean;
} {
    return {
        contact: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.contact)),
        name: value.name,
        education: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.education)),
        email: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.email)),
        experience: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.experience)),
        totalSkills: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.totalSkills)),
        isComplete: value.isComplete
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    requiredSkills: Array<_Skill>;
}): {
    title: string;
    description: string;
    requiredSkills: Array<Skill>;
} {
    return {
        title: value.title,
        description: value.description,
        requiredSkills: from_candid_vec_n17(_uploadFile, _downloadFile, value.requiredSkills)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearsOfExperience: bigint;
    contactInfo: [] | [string];
    name: string;
    education: [] | [Array<_Education>];
    workExperience: [] | [Array<_WorkExperience>];
    certifications: [] | [Array<string>];
    skills: [] | [Array<string>];
}): {
    yearsOfExperience: bigint;
    contactInfo?: string;
    name: string;
    education?: Array<Education>;
    workExperience?: Array<WorkExperience>;
    certifications?: Array<string>;
    skills?: Array<string>;
} {
    return {
        yearsOfExperience: value.yearsOfExperience,
        contactInfo: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.contactInfo)),
        name: value.name,
        education: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.education)),
        workExperience: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.workExperience)),
        certifications: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.certifications)),
        skills: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.skills))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): SkillLevel {
    return "intermediate" in value ? SkillLevel.intermediate : "beginner" in value ? SkillLevel.beginner : "advanced" in value ? SkillLevel.advanced : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    technical: null;
} | {
    softSkills: null;
}): SkillCategory {
    return "technical" in value ? SkillCategory.technical : "softSkills" in value ? SkillCategory.softSkills : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n18(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resume>): Promise<Array<Resume>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Resume_n25(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobRole>): Array<JobRole> {
    return value.map((x)=>from_candid_JobRole_n39(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SkillCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillCategory): _SkillCategory {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SkillLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): _SkillLevel {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Skill_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): _Skill {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WorkExperience> | null): [] | [Array<_WorkExperience>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Education> | null): [] | [Array<_Education>] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Skill> | null): [] | [Array<_Skill>] {
    return value === null ? candid_none() : candid_some(to_candid_vec_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    level: SkillLevel;
    category: SkillCategory;
}): {
    name: string;
    level: _SkillLevel;
    category: _SkillCategory;
} {
    return {
        name: value.name,
        level: to_candid_SkillLevel_n11(_uploadFile, _downloadFile, value.level),
        category: to_candid_SkillCategory_n13(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact?: string;
    name: string;
    education?: string;
    email?: string;
    experience?: string;
    totalSkills?: bigint;
    isComplete: boolean;
}): {
    contact: [] | [string];
    name: string;
    education: [] | [string];
    email: [] | [string];
    experience: [] | [string];
    totalSkills: [] | [bigint];
    isComplete: boolean;
} {
    return {
        contact: value.contact ? candid_some(value.contact) : candid_none(),
        name: value.name,
        education: value.education ? candid_some(value.education) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        experience: value.experience ? candid_some(value.experience) : candid_none(),
        totalSkills: value.totalSkills ? candid_some(value.totalSkills) : candid_none(),
        isComplete: value.isComplete
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == SkillLevel.intermediate ? {
        intermediate: null
    } : value == SkillLevel.beginner ? {
        beginner: null
    } : value == SkillLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillCategory): {
    technical: null;
} | {
    softSkills: null;
} {
    return value == SkillCategory.technical ? {
        technical: null
    } : value == SkillCategory.softSkills ? {
        softSkills: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Skill>): Array<_Skill> {
    return value.map((x)=>to_candid_Skill_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
